In [5]:
#we import numpy when working with arrays that contain number values
import numpy as np

In [6]:
myList = [1,2,3,4,5,6]
print(type(myList))
print(myList)

<class 'list'>
[1, 2, 3, 4, 5, 6]


In [7]:
#to change a list into an array you do the following
quortors = np.array(myList)

In [8]:
print(quortors)

[1 2 3 4 5 6]


In [9]:
#2D array is a 2 dimension array
#first we have created a list and then changed the list in an array
#we did this by referencing the "np.array function" and pass the variable the2D into that function
the2D = [[1,2,3],[4,5,6],[7,8,9]]

my2D = np.array(the2D)

my2D

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
my2D.shape

(3, 3)

In [11]:
#when we call in arange. 11 wont be called in. 2 is the step size. 0+2 2+2 4+2 6+2 8+2
#press shist tab to understand the brackets
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [12]:
#dummy values
np.zeros((4,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [13]:
dummy  = np.zeros((4,10))
dummy.shape

(4, 10)

In [14]:
#10 items in the row
#4 items in the column
dummy

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [15]:
#a dummy can be of zeros or ones
np.ones((5,5))

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
#one dimension array
#one dimension you ony need a pair of brackets else two pairs
np.ones(4) * 60

array([60., 60., 60., 60.])

In [17]:
#linearly spaced arrays return numbers over a specified interval
#zero is the start, ten is the stop
#there are three numbers that are eavenly spaced
#run this code and share the screenshot => np.linespace(0,10,20) now ask for 100 and 11
#check the length of the arrat => len(np.linspace(0,10,20)

np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [18]:
dummy2 = np.linspace(0,10,20)
          
print(len(dummy2))

20


In [19]:
#to generate random numbers in a given matrix/shape
#can be 1D or 2D
#numbers btw 0-1
np.random.rand(1)

array([0.89421062])

In [20]:
np.random.rand(5,5)

array([[0.36074427, 0.66583817, 0.47189289, 0.99254124, 0.13194956],
       [0.13321863, 0.17234698, 0.79076859, 0.40202366, 0.40218513],
       [0.55496164, 0.00866872, 0.88921192, 0.16012989, 0.94405613],
       [0.96474505, 0.1578715 , 0.15930137, 0.9094632 , 0.34451003],
       [0.99586348, 0.50125303, 0.75089779, 0.87911479, 0.01196576]])

In [21]:
#int in this case has come in because we want whole numbers
np.random.randint(1,100,10)

array([72,  8, 42, 87, 49,  6, 81, 65, 60, 14])

In [22]:
valueMinMax = np.random.randint(1,100,10)




valueMinMax

array([87, 79, 10, 19, 70, 58, 85, 10, 84, 81])

In [23]:
valueMinMax.min()

10

In [24]:
valueMinMax.max()

87

In [25]:
#this will give us the index location of the minimum value
#arg stands for arguement
valueMinMax.argmin()

2

In [26]:
#this will give us the index location of the maximum value
valueMinMax.argmax()

0

In [29]:
#this is how you replace something in an array
#arr = np.array([1,3,5,7])

#search = np.searchsorted(arr,[2,4,6])

#print(search)

[1 2 3]


In [30]:
#how to sort an array
arr2 = np.array([3,1,0,7,6,9])
np.sort(arr2)

array([0, 1, 3, 6, 7, 9])

In [32]:
#this is how you add arrays
#the length in both arrays should be the same
twiga = [1,2,3,4,5]
hello = [6,7,8,9,10]

sumTotal = np.add(twiga, hello)

print(sumTotal)

[ 7  9 11 13 15]
